In [3]:
#Random Number Generator
import numpy as np
np.random.rand(4,3)

array([[0.9778895 , 0.87909281, 0.45509056],
       [0.09006615, 0.6073439 , 0.47318136],
       [0.07962548, 0.44904737, 0.86995148],
       [0.84301558, 0.19276011, 0.73813775]])

In [4]:
import numpy as np
np.random.rand(3)

array([0.60989687, 0.44517457, 0.37067476])

In [5]:
import numpy as np
np.random.rand(1,3)

array([[0.17722826, 0.90346829, 0.6192153 ]])

In [6]:
import numpy as np
np.random.rand(1)

array([0.67421448])